### ISSUE TITLE
Avoid committing system files

### ISSUE THREAD

**Issue by wajeehmisbahkhan** [M1keZulu/NodeJS-GoogleDSC#3]
.DS_Store is a mac specific file which should not be present in your version control. You can avoid accidentally committing it by adding it to a .gitignore file. Here is a list of gitignore templates which can be useful:
https://github.com/github/gitignore

If you are working on a Node project on a Windows machine, you would pick Node.gitignore from the root and add all of the content to your project's .gitignore and additionally Windows.gitignore present in the Global folder. If a partner joins you who works on a Mac, you would also include the macOS.gitignore file's content.

**Comment by M1keZulu** [comment]
Issue #3 Resolved.

**Comment by wajeehmisbahkhan** [comment]
You can just say closes #3 and it will do that. The word issue is not required as the number is always unique to an issue or pull request.
