### ISSUE TITLE
Missing images

### ISSUE THREAD

**Issue by wajeehmisbahkhan** [M1keZulu/NodeJS-GoogleDSC#4]
Portfolio images could not be found. Was this intended or did you forget to commit them?

**Comment by M1keZulu** [comment]
Sorry! With all the pending final assignments, got occupied with a lot of stuff and was unable to create portfolio images. However, I shifted my attention to creating a new responsive website while learning Bootstrap. I have made and will be making commits to this repository. Currently, I have made the initial commits with progress that I have made with the Navbar and responsiveness. I will also be adding dummy images in that portfolio as well. As far as the concept for rendering images and HTML with server-side using NodeJS goes, I have grasped it and implemented it in both portfolio projects to some extent.
